###
### Server config: IP-Address and port to listen to.
###

server:
    ip: 0.0.0.0
    http:
        domain: ca.adito.local
        port: 8080
    ocsp:
        domain: ca.adito.local
        port: 2560



###
### CA config: Passphrase for CA Key
###

ca:
    root:
        passphrase: yyyy
        days: 3650
        country: DE
        state: Bayern
        locality: Geisenhausen
        organization: ADITO Software GmbH
        commonname: Root CA
    intermediate:
        passphrase: yyyy
        days: 3650
        country: DE
        state: Bayern
        locality: Geisenhausen
        organization: ADITO Software GmbH
        commonname: Intermediate CA
        ocsp:
            passphrase: yyyy
            country: DE
            url: "http://ca.adito.local:2560"
        crl:
            url: "http://ca.adito.local:8080/public/ca/intermediate/crl"


###
### Settings for end user certificates
###
cert:
    lifetime_default: 1
    lifetime_max: 365
